version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-dep-{{ checksum "yarn.lock" }}
            - yarn-dep-

      - restore_cache:
          keys:
            - gems-dep-{{ checksum "Gemfile.lock" }}
            - gems-dep-

      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build images
          command: |
            docker-compose build

      - run:
          name: Bundle install to vendor/bundle
          command: docker-compose run --rm web bundle install --path vendor/bundle -j4

      - run:
          name: Create DB, apply migration and seeding data (with verbose option) then check log and real data
          command: |
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails --verbose --trace=stdout db:create
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails --verbose --trace=stdout db:migrate
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails --verbose --trace=stdout db:seed
            cat log/test.log
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails --verbose --trace=stdout authors

      - save_cache:
          paths:
            - vendor/bundle
          key: gems-dep-{{ checksum "Gemfile.lock" }}

      - run:
          name: Create asset's manifest with dependency installation
          command: |
            docker-compose run --rm web yarn
            docker-compose run --rm web bundle exec rails webpacker:compile
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails --verbose --trace=stdout authors

      - save_cache:
          paths:
            - node_modules
          key: yarn-dep-{{ checksum "yarn.lock" }}

      - run:
          name: Run tests
          command: |
            docker-compose run --rm -e RAILS_ENV=test web bundle exec rails --verbose --trace=stdout authors
            docker-compose run --rm web bundle exec rspec
