default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password: S1r1pGiy9E*SQCpCL

development:
  <<: *default
  database: circleci_databasecleaner_experiment_development

test:
  <<: *default
  database: circleci_databasecleaner_experiment_test

production:
  <<: *default
  database: circleci_databasecleaner_experiment_production
  username: circleci_databasecleaner_experiment
  password: <%= ENV['CIRCLECI_DATABASECLEANER_EXPERIMENT_DATABASE_PASSWORD'] %>
